### ISSUE TITLE
Instructions install wrong version of PyQt in mac

### ISSUE THREAD

**Issue by jasongoodwin** [jrgp/pyqt-zk-inspector#1]
PyQt5 is the default version of PyQt installed so this app doesn't work with provided instructions.
I executed this:

```
    brew install pyqt qt
    sudo pip install Kazoo
```

everything is installed

```
$ brew install pyqt qt
Warning: pyqt 5.9_1 is already installed
Warning: qt 5.9.1 is already installed
```

and

```
$ sudo -H pip install Kazoo
Requirement already satisfied: Kazoo in /Library/Python/2.7/site-packages
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from Kazoo)
```

When I try to run the app python complains about the pyqt4 dependency being missing.

```
$ ./inspector.py
Traceback (most recent call last):
  File "./inspector.py", line 3, in <module>
    from qtinspector.cli import main
  File "/Users/jasongoodwin/Development/tools/pyqt-zk-inspector/qtinspector/cli.py", line 1, in <module>
    from mainwindow import MainWindow
  File "/Users/jasongoodwin/Development/tools/pyqt-zk-inspector/qtinspector/mainwindow.py", line 3, in <module>
    from PyQt4 import QtGui, QtCore, uic
ImportError: No module named PyQt4
```
I think this is because PyQt5 is default - I can import it via the repl but not PyQt4.
I found a recipe for PyQt4. Still haven't resolved my env issues.
```
brew install cartr/qt4/pyqt
```

**Comment by jasongoodwin** [comment]
Adding this to my env seems to work.
`export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH`

I'd just update the instructions.
